services:
  - type: web
    name: ihere-lets-go
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /tmp/finance.db
